name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - services/go/api-golang
          - services/node/api-node
          - services/python/load-generator-python
          - services/react/client-react

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: image
        run: |
          IMAGE_NAME=$(echo "${{ matrix.service }}" | tr '/' '-')
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        working-directory: capstone/${{ matrix.service }}
        run: |
          docker build \
          -t ghcr.io/${{ github.repository }}/${{ steps.image.outputs.name }}:latest \
          -t ghcr.io/${{ github.repository }}/${{ steps.image.outputs.name }}:${{ github.ref_name }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ steps.image.outputs.name }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ steps.image.outputs.name }}:${{ github.ref_name }}